Login btn 2
lukso-network/wallet.universalprofile.cloud pull request #21
Opened 2022-09-16 10:23 UTC by skimaharvey

2022-09-20 16:26 UTC, Hugoo requested changes
Could you also put a screenshot when you do UI changes? It helps to see things. Otherwise we have to clone and run locally to see the changes.

2022-09-20 16:26 UTC, Hugoo commented on components/LoginBtn/LoginBtn.tsx
> +    </>
```suggestion
      <Link href="/connect-wallets">
        <button className="flex items-center rounded-lg text-deepPink bg-white py-1 px-4">
          <span className="mx-2 text-sm">Connect</span>
        </button>
      </Link>
```

2022-09-20 16:26 UTC, Hugoo commented on components/LoginBtn/LoginBtn.tsx
> +  const addressFirstFour = () => walletAddress?.slice(2, 6);
why make it a function?

Why not just

```suggestion
  const addressFirstFour = walletAddress?.slice(2, 6);
```

2022-09-20 16:26 UTC, Hugoo commented on components/LoginBtn/LoginBtn.tsx
> +import Link from 'next/link';
I suggest to put external libs at the top

2022-09-20 16:26 UTC, Hugoo commented on components/LoginBtn/LoginBtn.tsx
> +  };
i think this should go in its own component - but lets keep it here for now

2022-09-20 16:26 UTC, Hugoo commented on components/LoginBtn/LoginBtn.tsx
> +  };
i think these utils function should be put outside of the component, as they can be used elsewhere. Not just here. You could import this function here

2022-09-21 16:44 UTC, skimaharvey commented
<img width="1394" alt="Screenshot 2022-09-21 at 17 43 22" src="https://user-images.githubusercontent.com/64636974/191563163-d764da9e-6cf6-45b3-afe1-e088776ae8a1.png">

2022-09-22 13:36 UTC, Hugoo approved these changes

2022-09-22 13:37 UTC, merged